# anthropic_integration_v45.py
"""
YSenseAI v4.5 - Anthropic API Integration
Layer extraction, distillation, and collaborative dialogue.

Model is configured with ANTHROPIC_MODEL (default: claude-haiku-4-5).
When no API key is present the client runs in offline fallback mode and
returns a clearly labelled placeholder instead of silently inventing content.
"""

import os
import sys
from pathlib import Path
from typing import Dict, List

# Add parent directory to path for config
sys.path.append(str(Path(__file__).parent.parent))
try:
    from config import ANTHROPIC_API_KEY, ANTHROPIC_MODEL
except ImportError:
    from dotenv import load_dotenv

    load_dotenv()
    ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
    ANTHROPIC_MODEL = os.getenv("ANTHROPIC_MODEL", "claude-haiku-4-5")

try:
    import anthropic
except ImportError:  # SDK not installed; offline mode only
    anthropic = None

OFFLINE_NOTICE = (
    "[offline mode] No ANTHROPIC_API_KEY configured, so this response was not "
    "generated by an AI model. Add a key to .env to enable AI analysis."
)


class AnthropicClient:
    """Anthropic API client for YSenseAI"""

    def __init__(self):
        self.api_key = ANTHROPIC_API_KEY
        self.model = ANTHROPIC_MODEL

        if not self.api_key or anthropic is None:
            if not self.api_key:
                print("⚠️ ANTHROPIC_API_KEY not found. Using offline fallback mode.")
            else:
                print("⚠️ anthropic SDK not installed. Using offline fallback mode.")
            self.use_fallback = True
            self.client = None
        else:
            self.use_fallback = False
            self.client = anthropic.Anthropic(api_key=self.api_key)

    def create_completion(
        self, messages: List[Dict], temperature: float = 0.7, max_tokens: int = 1000
    ) -> str:
        """Create completion using the Anthropic Messages API"""

        if self.use_fallback:
            return self._fallback_response(messages)

        try:
            system_message = ""
            anthropic_messages = []

            for msg in messages:
                if msg["role"] == "system":
                    system_message = msg["content"]
                else:
                    anthropic_messages.append(
                        {"role": msg["role"], "content": msg["content"]}
                    )

            if not anthropic_messages:
                anthropic_messages = [{"role": "user", "content": "Hello"}]

            request = {
                "model": self.model,
                "max_tokens": max_tokens,
                "messages": anthropic_messages,
            }
            if system_message:
                request["system"] = system_message
            # Newer models reject sampling parameters; only send temperature
            # when the caller changed it from the default.
            if temperature != 0.7:
                request["temperature"] = temperature

            response = self.client.messages.create(**request)

            for block in response.content:
                if block.type == "text":
                    return block.text
            return ""

        except Exception as e:  # noqa: BLE001 - surface any API failure as fallback
            print(f"Anthropic API Error: {e}")
            return self._fallback_response(messages)

    def generate_response(self, prompt: str, max_tokens: int = 1000) -> str:
        """Generate response from text prompt"""
        messages = [{"role": "user", "content": prompt}]
        return self.create_completion(messages, 0.7, max_tokens)

    def _fallback_response(self, messages: List[Dict]) -> str:
        """Fallback response when the API is unavailable.

        Deliberately generic: the previous version returned marketing copy
        here, which made offline output look like real analysis.
        """
        return OFFLINE_NOTICE


class AnthropicOrchestratorAgent:
    """Base class for role-based analysis agents using Anthropic"""

    def __init__(self, role: str, activation_phrase: str, expertise: str):
        self.role = role
        self.activation_phrase = activation_phrase
        self.expertise = expertise
        self.client = AnthropicClient()

    def analyze(self, wisdom_drop: Dict, context: str = "") -> str:
        """Analyze wisdom drop from agent's perspective"""

        prompt = f"""
        Role: {self.role}
        Expertise: {self.expertise}

        Analyze this wisdom contribution:
        {wisdom_drop}

        Context: {context}

        Provide your analysis focusing on {self.activation_phrase}.
        Be concise but insightful (max 150 words).
        """

        messages = [
            {
                "role": "system",
                "content": f"You are {self.role} of YSenseAI, providing expert analysis.",
            },
            {"role": "user", "content": prompt},
        ]

        return self.client.create_completion(messages, temperature=0.7, max_tokens=200)


def test_anthropic_integration():
    """Manual check of the Anthropic API connection"""

    print("🚀 Testing YSenseAI v4.5 Anthropic Integration")
    print("=" * 60)

    client = AnthropicClient()
    print(f"Model: {client.model} | offline fallback: {client.use_fallback}")

    messages = [
        {"role": "system", "content": "You are a helpful AI assistant for YSenseAI."},
        {"role": "user", "content": "Say 'Hello from YSenseAI v4.5!' in a friendly way."},
    ]
    response = client.create_completion(messages, max_tokens=100)
    print(f"Response: {response}")

    print("\n✅ Anthropic Integration Test Complete!")


if __name__ == "__main__":
    test_anthropic_integration()
